// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/movies/[id].tsx";
import * as $5 from "./routes/movies/[id]/comments.tsx";
import * as $6 from "./routes/movies/_middleware.ts";
import * as $7 from "./routes/movies/index.tsx";
import * as $8 from "./routes/rate-a-movie.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/api/joke.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/movies/[id].tsx": $4,
    "./routes/movies/[id]/comments.tsx": $5,
    "./routes/movies/_middleware.ts": $6,
    "./routes/movies/index.tsx": $7,
    "./routes/rate-a-movie.tsx": $8,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
